org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
fabric_api_version=0.161.0+26.3
loom_version=1.18.1
moddev_version=2.0.147
cloth_config_version=26.3.158
modmenu_version=21.0.0-beta.1
mixinextras_version=0.5.5
neo_version=26.3.0.16-beta

mod_version=1.1.1+26.3
maven_group=net.catcraft
archives_base_name=catcraft-companion
