license="MIT"
issueTrackerURL="https://github.com/VBodetti/catcraft-moderation-companion/issues"

[[mods]]
modId="catcraft_moderation_companion"
version="${version}"
displayName="CatCraft Companion"
displayURL="https://www.catcraft.net/"
logoFile="icon.png"
authors="B0_Deadly"
description='''
Client-side command navigation, player profiles, staff utilities, and conflict-aware chat enhancements for CatCraft players.
'''

[[mixins]]
config="ccmc-core.mixins.json"

[[mixins]]
config="ccmc.mixins.json"

[[dependencies.catcraft_moderation_companion]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.catcraft_moderation_companion]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.catcraft_moderation_companion]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},)"
ordering="AFTER"
side="CLIENT"
